name: Big Data Revenue Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      hadoop:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        ports:
          - 9000:9000
        environment:
          - CLUSTER_NAME=test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Project
        run: |
          mvn clean package

      - name: Check Hadoop CLI
        run: |
          hdfs version

      - name: Setup Environment
        run: |
          ./scripts/shell/setup_environment.sh

      - name: Deploy to Cluster
        run: |
          ./scripts/shell/deploy_to_cluster.sh

      - name: Run Pipeline
        run: |
          ./scripts/shell/run_pipeline.sh

