name: Big Data Revenue Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      HADOOP_VERSION: 3.3.6
      HADOOP_HOME: ${{ github.workspace }}/hadoop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Download and extract Hadoop
        run: |
          wget https://downloads.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz
          tar -xzf hadoop-${HADOOP_VERSION}.tar.gz
          mv hadoop-${HADOOP_VERSION} $HADOOP_HOME

      - name: Set up environment variables
        run: |
          echo "HADOOP_HOME=$HADOOP_HOME" >> $GITHUB_ENV
          echo "$HADOOP_HOME/bin" >> $GITHUB_PATH
          echo "$HADOOP_HOME/sbin" >> $GITHUB_PATH

      - name: Check Hadoop CLI
        run: |
          hdfs version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Project
        run: |
          mvn clean package

      - name: Setup Environment
        run: |
          ./scripts/shell/setup_environment.sh

      - name: Deploy to Cluster
        run: |
          ./scripts/shell/deploy_to_cluster.sh

      - name: Run Pipeline
        run: |
          ./scripts/shell/run_pipeline.sh

